# Generated by Django 5.0.6 on 2024-06-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandlerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandler',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
